--- themes for books of school 1 and 2 and 3 
INSERT INTO book_theme (theme, book_id)
VALUES
    ('Fiction', 1),
    ('Drama', 1),
    ('Romance', 1),
    ('Coming of Age', 2),
    ('Fiction', 2),
    ('Adventure', 2),
    ('Adventure', 3),
    ('Fantasy', 3),
    ('Science Fiction', 3),
    ('Mystery', 4),
    ('Thriller', 4),
    ('Horror', 4),
    ('Adventure', 5),
    ('Fiction', 5),
    ('Classic', 5),
    ('Classic', 6),
    ('Drama', 6),
    ('Romance', 6),
    ('Mystery', 7),
    ('Thriller', 7),
    ('Horror', 7),
    ('Adventure', 8),
    ('Classic', 8),
    ('Biography', 8),
    ('Biography', 9),
    ('Fiction', 9),
    ('History', 9),
    ('Science Fiction', 10),
    ('Thriller', 10),
    ('Fantasy', 10),
    ('Fantasy', 11),
    ('Adventure', 11),
    ('Coming of Age', 11),
    ('Coming of Age', 12),
    ('Romance', 12),
    ('Mystery', 12),
    ('Mystery', 13),
    ('Thriller', 13),
    ('Horror', 13);
INSERT INTO book_theme (theme, book_id)
VALUES
    ('Fantasy', 14),
    ('Adventure', 14),
    ('Classic', 14),
    ('Mystery', 15),
    ('Adventure', 15),
    ('Fantasy', 15),
    ('Adventure', 16),
    ('Drama', 16),
    ('Coming of Age', 16),
    ('Mystery', 17),
    ('Drama', 17),
    ('Thriller', 17),
    ('Adventure', 18),
    ('Romance', 18),
    ('Drama', 18),
    ('Adventure', 19),
    ('Science Fiction', 19),
    ('Dystopia', 19),
    ('Classic', 20),
    ('Drama', 20),
    ('Coming of Age', 20),
    ('Drama', 21),
    ('Classic', 21),
    ('Dystopia', 22),
    ('Science Fiction', 22),
    ('Adventure', 22),
    ('Mystery', 23),
    ('Drama', 23),
    ('Thriller', 23),
    ('Adventure', 24),
    ('Drama', 24),
    ('Coming of Age', 24),
    ('Mystery', 25),
    ('Drama', 25),
    ('Thriller', 25),
    ('Adventure', 26),
    ('Romance', 26),
    ('Drama', 26),
    ('Adventure', 27),
    ('Science Fiction', 27),
    ('Dystopia', 27),
    ('Classic', 28),
    ('Drama', 28),
    ('Coming of Age', 28),
    ('Fantasy', 29),
    ('Adventure', 29),
    ('Classic', 29),
    ('Adventure', 30),
    ('Fantasy', 30),
    ('Children', 30),
    ('Classic', 31),
    ('Science Fiction', 31),
    ('Gothic', 31),
    ('Adventure', 32),
    ('Fantasy', 32),
    ('Children', 32),
    ('Adventure', 33),
    ('Science Fiction', 33),
    ('Gothic', 34),
    ('Horror', 34),
    ('Classic', 34),
    ('Dystopia', 35),
    ('Science Fiction', 35),
    ('Dystopia', 36),
    ('Science Fiction', 36),
    ('Science Fiction', 37);

INSERT INTO book_theme (theme, book_id)
VALUES
    ('Science Fiction', 38),
    ('Adventure', 38),
    ('Science Fiction', 39),
    ('Mystery', 39),
    ('Science Fiction', 40),
    ('Classic', 40),
    ('Adventure', 41),
    ('Fantasy', 41),
    ('Classic', 41),
    ('Science Fiction', 42),
    ('Science', 42),
    ('Adventure', 43),
    ('Classic', 43),
    ('Fantasy', 44),
    ('Adventure', 44),
    ('Children', 44),
    ('Adventure', 45),
    ('Dystopia', 45),
    ('Thriller', 46),
    ('Mystery', 46),
    ('Fantasy', 47),
    ('Adventure', 47),
    ('Children', 47),
    ('Romance', 48),
    ('Classic', 48),
    ('Adventure', 49),
    ('Fiction', 49),
    ('Classic', 49),
    ('Fantasy', 50),
    ('Adventure', 50),
    ('Children', 50),
    ('Dystopia', 51),
    ('Science Fiction', 51),
    ('Fantasy', 52),
    ('Adventure', 52),
    ('Classic', 53),
    ('Adventure', 53),
    ('Fantasy', 54),
    ('Adventure', 54),
    ('Coming of Age', 55),
    ('Romance', 55),
    ('Drama', 55),
    ('Mystery', 56),
    ('Thriller', 56),
    ('Romance', 57),
    ('Classic', 57),
    ('Drama', 57),
    ('Gothic', 58),
    ('Romance', 58),
    ('Classic', 58),
    ('Romance', 59),
    ('Drama', 59),
    ('Classic', 59),
    ('Gothic', 60),
    ('Romance', 60),
    ('Classic', 60);
INSERT INTO book_theme (theme, book_id)
VALUES
    ('Romance', 61),
    ('Classic', 61),
    ('Drama', 61),
    ('Classic', 62),
    ('Romance', 63),
    ('Drama', 63),
    ('Classic', 63),
    ('Romance', 64),
    ('Drama', 64),
    ('Classic', 64),
    ('Gothic', 65),
    ('Adventure', 65),
    ('Classic', 65),
    ('Mystery', 66),
    ('Adventure', 66),
    ('Classic', 66),
    ('Religion', 67),
    ('Classic', 67),
    ('Adventure', 68),
    ('Coming of Age', 68),
    ('Classic', 68),
    ('Adventure', 69),
    ('Children', 69),
    ('Classic', 69),
    ('Romance', 70),
    ('Drama', 70),
    ('Classic', 70),
    ('Classic', 71),
    ('Adventure', 71),
    ('Classic', 72),
    ('Fantasy', 72),
    ('Adventure', 72),
    ('Coming of Age', 73),
    ('Drama', 73),
    ('Classic', 73),
    ('Adventure', 74),
    ('Drama', 74),
    ('Classic', 74),
    ('Coming of Age', 75),
    ('Drama', 75),
    ('Classic', 75),
    ('Adventure', 76),
    ('Classic', 76),
    ('Adventure', 77),
    ('Mystery', 77),
    ('Classic', 77),
    ('Adventure', 78),
    ('Fantasy', 78),
    ('Children', 78),
    ('Adventure', 79),
    ('Children', 79),
    ('Classic', 79),
    ('Adventure', 80),
    ('Classic', 80),
    ('Adventure', 81),
    ('Classic', 81),
    ('Adventure', 82),
    ('Classic', 82),
    ('Adventure', 83),
    ('Classic', 83),
    ('Fantasy', 84),
    ('Adventure', 84),
    ('Children', 84),
    ('Fantasy', 85),
    ('Adventure', 85),
    ('Children', 85),
    ('Fantasy', 86),
    ('Adventure', 86),
    ('Children', 86),
    ('Fantasy', 87),
    ('Adventure', 87),
    ('Children', 87),
    ('Fantasy', 88),
    ('Adventure', 88),
    ('Children', 88),
    ('Classic', 89),
    ('Drama', 89),
    ('Tragedy', 89),
    ('Coming of Age', 90),
    ('Drama', 90),
    ('Classic', 90),
    ('Classic', 91),
    ('Drama', 91),
    ('Romance', 92),
    ('Classic', 92),
    ('Tragedy', 92),
    ('Romance', 93),
    ('Tragedy', 93),
    ('Classic', 93),
    ('Tragedy', 94),
    ('Drama', 94),
    ('Classic', 94),
    ('Adventure', 95),
    ('Classic', 95),
    ('Drama', 96),
    ('Romance', 96),
    ('Classic', 96),
    ('Drama', 97),
    ('Romance', 97),
    ('Classic', 97),
    ('Gothic', 98),
    ('Horror', 98),
    ('Classic', 98),
    ('Fantasy', 99),
    ('Adventure', 99),
    ('Children', 99),
    ('Adventure', 100),
    ('Children', 100),
    ('Fantasy', 100),
    ('Adventure', 101),
    ('Fantasy', 101),
    ('Children', 101),
    ('Adventure', 102),
    ('Fantasy', 102),
    ('Children', 102);
