-- AUTHORS --> OK
--- authors for books of shcool 1 and 2
INSERT INTO book_author (author, book_id)
VALUES
  ('Jane Austen', 1),
  ('J.D. Salinger', 2),
  ('J.R.R. Tolkien', 3),
  ('George Orwell', 4),
  ('Paulo Coelho', 5),
  ('Charles Dickens', 6),
  ('Virginia Woolf', 7),
  ('Herman Melville', 8),
  ('Oscar Wilde', 9),
  ('Mary Shelley', 10),
  ('George R.R. Martin', 11),
  ('John Green', 12),
  ('Gillian Flynn', 13),
  ('C.S. Lewis', 14),
  ('Dan Brown', 15),
  ('Khaled Hosseini', 16),
  ('Markus Zusak', 17),
  ('Sue Monk Kidd', 18),
  ('Cormac McCarthy', 19),
  ('Sylvia Plath', 20),
  ('Kathryn Stockett', 21),
  ('Suzanne Collins', 22),
  ('Dan Brown', 23),
  ('Khaled Hosseini', 24),
  ('Markus Zusak', 25),
  ('Sue Monk Kidd', 26),
  ('Cormac McCarthy', 27),
  ('Sylvia Plath', 28),
  ('Kathryn Stockett', 29),
  ('Lewis Carroll', 30),
  ('Mary Shelley', 31),
  ('L. Frank Baum', 32),
  ('Arthur Conan Doyle', 33),
  ('Bram Stoker', 34),
  ('Aldous Huxley', 35),
  ('H.G. Wells', 36),
  ('H.G. Wells', 37);

-- Insert authors for each book
INSERT INTO book_author (author, book_id)
VALUES
  ('H.G. Wells', 38),
  ('Arthur Conan Doyle', 39),
  ('H.G. Wells', 40),
  ('Jules Verne', 41),
  ('Edwin A. Abbott', 42),
  ('Joseph Conrad', 43),
  ('J.K. Rowling', 44),
  ('Suzanne Collins', 45),
  ('Stieg Larsson', 46),
  ('C.S. Lewis', 47),
  ('Jane Austen', 48),
  ('J.D. Salinger', 49),
  ('J.R.R. Tolkien', 50),
  ('Aldous Huxley', 51),
  ('J.R.R. Tolkien', 52),
  ('Homer', 53),
  ('George R.R. Martin', 54),
  ('John Green', 55),
  ('Gillian Flynn', 56),
  ('Jane Austen', 57),
  ('Emily Bronte', 58),
  ('Jane Austen', 59),
  ('Jane Austen', 60),
  ('Charlotte Bronte', 58);
-- Insert authors for each book
INSERT INTO book_author (author, book_id)
VALUES
  ('Edith Wharton', 61),
  ('Harriet Beecher Stowe', 62),
  ('D.H. Lawrence', 63),
  ('F. Scott Fitzgerald', 64),
  ('Joseph Conrad', 65),
  ('Wilkie Collins', 66),
  ('Multiple Authors', 67),
  ('Mark Twain', 68),
  ('Robert Louis Stevenson', 69),
  ('Jane Austen', 70),
  ('Charles Dickens', 71),
  ('Charles Dickens', 72),
  ('Louisa May Alcott', 73),
  ('Charles Dickens', 74),
  ('Charles Dickens', 75),
  ('Miguel de Cervantes', 76),
  ('Arthur Conan Doyle', 77),
  ('L. Frank Baum', 78),
  ('Mark Twain', 79),
  ('Robert Louis Stevenson', 80),
  ('Herman Melville', 81),
  ('Daniel Defoe', 82),
  ('Jack London', 83),
  ('J.K. Rowling', 84),
  ('J.K. Rowling', 85),
  ('J.K. Rowling', 86),
  ('C.S. Lewis', 87),
  ('Philip Pullman', 88),
  ('William Shakespeare', 89),
  ('Charles Dickens', 90),
  ('F. Scott Fitzgerald', 91),
  ('Homer', 92),
  ('William Shakespeare', 93),
  ('William Shakespeare', 94),
  ('James Fenimore Cooper', 95),
  ('William Shakespeare', 96),
  ('William Shakespeare', 97),
  ('Bram Stoker', 98),
  ('George MacDonald', 99),
  ('Carlo Collodi', 100),
  ('E. Nesbit', 101),
  ('L. Frank Baum', 102);

---
--- extra 
/* INSERT INTO book_author (author, book_id)
VALUES
  ('Edith Wharton', 31),
  ('Harriet Beecher Stowe', 47),
  ('D.H. Lawrence', 42),
  ('F. Scott Fitzgerald', 23),
  ('Joseph Conrad', 28),
  ('Wilkie Collins', 37),
  ('Multiple Authors', 45),
  ('Mark Twain', 49),
  ('Robert Louis Stevenson', 26),
  ('Jane Austen', 33),
  ('Charles Dickens', 39); */
